verbosity:
  level:
    - high
    - medium
    - low

model:
  tfidf:
    architectures:
      - logistic
      - svm

  neural:
    architectures:
      - lstm
      - cnn
  
  transformer:
    architectures:
      - brian

dataset:
  train:
    path: ./dataset/train.jsonl
  test:
    path: ./dataset/test.jsonl
  split:
    train_size: 0.9
    val_size: 0.1

training:
  lr: 0.001
  batch_size: 4
  epochs: 80
  patience: 10
  classes: 4
  max_len: 128